In [118]:
import numpy as np

class Perceptron(object):
    """Impleents a perceptron network """
    
    def __init__(self,input_size,lr=1,epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
        
        
    def activation_fn(self,x):
        return 1 if x >= 0 else 0
    
    
    def predict(self,x):
        x = np.insert(x,0,1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    
    
    def fit(self,X,d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i],0,1)


In [119]:
X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]
    ])

In [120]:
d = np.array([0,0,0,1])


In [121]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [122]:
d

array([0, 0, 0, 1])

In [123]:
perceptron = Perceptron(input_size=2)


In [124]:
perceptron.W

array([0., 0., 0.])

In [125]:
perceptron.fit(X,d)

In [126]:
perceptron.W

array([-3.,  2.,  1.])

In [127]:

print(perceptron.W)

[-3.  2.  1.]


In [129]:
perceptron.predict(np.asarray([0,0]))

0

In [130]:
mp = Perceptron(5)
x = np.asarray([1,1,0,0,0])
mp.predict(x)

1

In [131]:
mp.activation_fn(10)

1

In [132]:
mp.W

array([0., 0., 0., 0., 0., 0.])

1) Perceptron class tanımınında var olan fonksiyonları kısaca tanıtınız.

init fonksiyonu
Öncelikle perceptron'u oluşturmamız gerekiyor. Ağırlık vektörünü hesaplayabilmek için kullanıcıdan kaç adet veri giliceğine dair girdi almamız gerekir. Sonrasında Sapmayı dahil edebilmek için girdi boyutunu arttırmamız gerekiyor. Devir sayısını ve Öğrenme oranını fonksiyona biz dahil ettik fakat parametre ile atanarakda oluşturulabilir.

activation_fn fonksiyonu
Aktivasyon fonksiyonuna elde ettiğimiz eşik değerini parametre olarak iletiriz. Girilen parametre >=0 dan ise geriye "1" değerini döndürürüz. Değil ise "0" değerini döndürüz. Aktivasyon foknsiyonumuz bu şekilde çıktı üretmiş olur.

predict fonksiyonu
Algılayıcı vasıtasıyla gelen girdiyi çalıştırarak çıktı üretmemizi sağlayan bir tahmin fonksiyonudur. Öncelikle Eğilim değeri eklenir ve sonrasında ise dizilerin çarpımı hesaplınır. Sonra elde edilen değer aktivasyon fonksiyonuna iletilir ve sonuç tahmin edilerek çıktı üretilir.

fit fonksiyonu
Bu fonksiyon bir eğitim fonksiyonudur. Öncelikle eğitim seti yenilenmeli ve ağırlığı devir sayımıza göre güncellemeliyiz. Sonrasında ağırlık değerini güncelleme işlemimi gerçekleştirirken ise sapmayı girdiye eklememiz gereklidir. Bu işlemler tamamlandıktan sonra ardından ise tahmin değerini oluşturmuş oluyoruz ve bu sayede hatamızı hesaplayabiliyoruz. Sonrasında da güncelleme kuralımızı uygulayarak eğitim fonksiyonumuzu tamamlamış olyoruz.



2- XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.

XOR İşlemi:

X = np.array([[0,0],[0,1],[1,0],[1,1]])

d = np.array([0,1,1,0])              --> girdiye uygun değerler girilmiştir.


perceptron = Perceptron(input_size=2)
perceptron.fit(X,d)

print(perceptron.W)              çıktı --> [ 0. -1.  0.]


predict fonksiyonu sonucu hesaplanan değerler:

perceptron.predict(np.asarray([0,0]))       çıktı --> 1
perceptron.predict(np.asarray([0,1]))       çıktı --> 1
perceptron.predict(np.asarray([1,0]))       çıktı --> 0
perceptron.predict(np.asarray([1,1]))       çıktı --> 0


GÖZLEM:

Sonuçları gözlemlediğimizde XOR işlemi yapıldığında predict sonuçlarının doğru çıktıları vermediğini gözlemlemiş oluyoruz. Bunun nedeni predict fonksiyonu yalnızca doğrusal ayrılabilen çıktılarda doğru sonuçlar üretebilmesidir. XOR işlemide doğrusal olarak ayrılamadı için kullanamamaktayız.

3- bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız.

İnput'u X değerleri ve Output'u ise d değerleri göstermektedir. X değeri de öğrencilerin imzalarını tutacağı için 40 adet imzayı dizi halinde tutmaktadır. Her öğrencinin 40 elemanlı imza dizisi bulunduğu için d değeri 40 olmalıdır. Bu değerlerin hepsi X dizisindeki imzaların öğrenciye ait karşılığıdır.
Bir öğrencinin imzası predict fonksiyonuna girdi olarak iletilir. Sonrasında ise gelen girdiler üzerinde gerekli işlemler yapılır ve imzaların hani öğrenciye ait olduğu tespit edilerek output verilir.


4- Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/ yorumunuzu yazınız.

Hata oranını tespit etmek için bir Error fonksiyonu oluştururdum. Bu fonksiyonda öncelikle yanlış deneme/toplam deneme işlemini yaparak elde edilen ondalıklı değeri yüzdelik olarak hesaplatırdım. Sonrasında ise elde edilen yüzdelik dilimi %100 değerinden çıkararak hata oranını tespit ederdim.